// Ce que la coquille Electron dit, dans les six langues.
//
// Un fichier plutôt qu'un par langue : c'est ce qui rend une clé manquante
// visible d'un coup d'œil, et c'est déjà la règle des dictionnaires du site.
//
// Ces textes ne peuvent pas passer par `useT` : ils s'affichent hors de React
// — dans une page `data:`, dans le menu près de l'horloge, dans une
// notification du système. Même situation que les notifications web et l'image
// de bilan, même réponse.

const { choisirLangue, REPLI } = require("./langue");

const TEXTES = {
  fr: {
    attenteTitre: "Authentification en cours",
    attenteCorps: "Terminez la connexion dans votre navigateur web.",
    attenteAuto: "Cette fenêtre se met à jour automatiquement une fois connecté.",
    attenteRien: "Rien ne se passe ?",
    attenteRouvrir: "Rouvrir le navigateur",
    attenteRetour: "Revenir à la connexion",
    portTitre: "CONNEXION IMPOSSIBLE",
    portCorps: "Une autre application Win or Workout est déjà ouverte sur cet ordinateur : probablement une ancienne version.",
    portConseil: "Fermez-la complètement, puis relancez celle-ci. Sans cela, c'est elle qui reçoit la connexion.",
    expireeTitre: "CONNEXION NON TERMINÉE",
    expireeCorps: "Le navigateur n'a pas rendu la connexion à l'application. Soit elle n'a pas été menée à son terme, soit le retour s'est perdu en chemin.",
    expireeReessayer: "Réessayer",
    expireeAutre: "Autre méthode",
    titreFenetreConnexion: "Connexion · Win or Workout",
    overlayTitre: "Overlay · Win or Workout",
    overlayJoue: "joué ce soir, hors menus",
    overlayPasDePartie: "pas de partie",
    overlaySiGagne: "Si gagné",
    overlaySiPerdu: "Si perdu",
    overlayEnAttente: "En attente",
    overlayConsigne: "Traîne-moi où tu veux, puis « Terminer ».",
    overlayPartieEnCours: "partie en cours",
    overlayJeuOuvert: "jeu ouvert ce soir, menus compris",
    overlayEscouade: "Escouade",
    trayOuvrir: "Ouvrir Win or Workout",
    trayOverlay: "Overlay en jeu",
    trayDossierCaptures: "Ouvrir le dossier des captures",
    trayLireEcran: "Lire les chiffres à l'écran",
    trayLirePendant: "Lire l'écran pendant la partie",
    trayBascule: "Afficher / masquer l'overlay",
    trayCapturer: "Capturer l'écran",
    veilleTitre: "Win or Workout continue en arrière-plan",
    veilleCorps: "Tes parties restent détectées. Clique sur l'icône près de l'horloge pour rouvrir, ou « Quitter » pour arrêter.",
    trayQuitter: "Quitter",
    captureFaite: "Capture enregistrée",
    captureRatee: "Capture impossible",
    captureRaisonInconnue: "raison inconnue",
  },
  en: {
    attenteTitre: "Signing you in",
    attenteCorps: "Finish signing in from your web browser.",
    attenteAuto: "This window updates on its own once you are signed in.",
    attenteRien: "Nothing happening?",
    attenteRouvrir: "Reopen the browser",
    attenteRetour: "Back to sign-in",
    portTitre: "CANNOT SIGN IN",
    portCorps: "Another Win or Workout app is already running on this computer, most likely an older version.",
    portConseil: "Close it completely, then start this one again. Otherwise it is the one that receives the sign-in.",
    expireeTitre: "SIGN-IN NOT COMPLETED",
    expireeCorps: "The browser never handed the sign-in back to the app. Either it was not finished, or the answer got lost on the way.",
    expireeReessayer: "Try again",
    expireeAutre: "Another way",
    titreFenetreConnexion: "Sign in · Win or Workout",
    overlayTitre: "Panel · Win or Workout",
    overlayJoue: "played tonight, menus excluded",
    overlayPasDePartie: "no match running",
    overlaySiGagne: "If you win",
    overlaySiPerdu: "If you lose",
    overlayEnAttente: "Owed",
    overlayConsigne: "Drag me anywhere, then hit « Done ».",
    overlayPartieEnCours: "match in progress",
    overlayJeuOuvert: "game open tonight, menus included",
    overlayEscouade: "Squad",
    trayOuvrir: "Open Win or Workout",
    trayOverlay: "In-game panel",
    trayDossierCaptures: "Open the screenshots folder",
    trayLireEcran: "Read the numbers on screen",
    trayLirePendant: "Read the screen during the match",
    trayBascule: "Show / hide the panel",
    trayCapturer: "Take a screenshot",
    veilleTitre: "Win or Workout keeps running in the background",
    veilleCorps: "Your matches are still being detected. Click the icon near the clock to reopen, or \u00ab Quit \u00bb to stop.",
    trayQuitter: "Quit",
    captureFaite: "Screenshot saved",
    captureRatee: "Screenshot failed",
    captureRaisonInconnue: "reason unknown",
  },
  es: {
    attenteTitre: "Iniciando sesión",
    attenteCorps: "Termina el inicio de sesión en tu navegador.",
    attenteAuto: "Esta ventana se actualiza sola en cuanto hayas entrado.",
    attenteRien: "¿No pasa nada?",
    attenteRouvrir: "Volver a abrir el navegador",
    attenteRetour: "Volver al inicio de sesión",
    portTitre: "NO SE PUEDE INICIAR SESIÓN",
    portCorps: "Ya hay otra aplicación Win or Workout abierta en este ordenador, probablemente una versión antigua.",
    portConseil: "Ciérrala del todo y vuelve a abrir esta. Si no, es ella la que recibe el inicio de sesión.",
    expireeTitre: "INICIO DE SESIÓN SIN TERMINAR",
    expireeCorps: "El navegador no ha devuelto el inicio de sesión a la aplicación. O no se llegó a completar, o la respuesta se perdió por el camino.",
    expireeReessayer: "Reintentar",
    expireeAutre: "Otro método",
    titreFenetreConnexion: "Iniciar sesión · Win or Workout",
    overlayTitre: "Recuadro · Win or Workout",
    overlayJoue: "jugado esta noche, sin menús",
    overlayPasDePartie: "sin partida",
    overlaySiGagne: "Si ganas",
    overlaySiPerdu: "Si pierdes",
    overlayEnAttente: "Pendiente",
    overlayConsigne: "Arrástrame donde quieras y pulsa « Terminar ».",
    overlayPartieEnCours: "partida en curso",
    overlayJeuOuvert: "juego abierto esta noche, con menús",
    overlayEscouade: "Escuadrón",
    trayOuvrir: "Abrir Win or Workout",
    trayOverlay: "Recuadro en el juego",
    trayDossierCaptures: "Abrir la carpeta de capturas",
    trayLireEcran: "Leer los números en pantalla",
    trayLirePendant: "Leer la pantalla durante la partida",
    trayBascule: "Mostrar / ocultar el recuadro",
    trayCapturer: "Capturar la pantalla",
    veilleTitre: "Win or Workout sigue funcionando en segundo plano",
    veilleCorps: "Tus partidas se siguen detectando. Haz clic en el icono junto al reloj para volver a abrirlo, o en « Salir » para pararlo.",
    trayQuitter: "Salir",
    captureFaite: "Captura guardada",
    captureRatee: "No se ha podido capturar",
    captureRaisonInconnue: "motivo desconocido",
  },
  de: {
    attenteTitre: "Anmeldung läuft",
    attenteCorps: "Schließ die Anmeldung in deinem Browser ab.",
    attenteAuto: "Dieses Fenster aktualisiert sich von selbst, sobald du angemeldet bist.",
    attenteRien: "Tut sich nichts?",
    attenteRouvrir: "Browser erneut öffnen",
    attenteRetour: "Zurück zur Anmeldung",
    portTitre: "ANMELDUNG NICHT MÖGLICH",
    portCorps: "Auf diesem Rechner läuft bereits eine andere Win-or-Workout-App, vermutlich eine ältere Version.",
    portConseil: "Schließ sie vollständig und starte diese neu. Sonst bekommt sie die Anmeldung.",
    expireeTitre: "ANMELDUNG NICHT ABGESCHLOSSEN",
    expireeCorps: "Der Browser hat die Anmeldung nicht an die App zurückgegeben. Entweder wurde sie nicht zu Ende geführt, oder die Antwort ging unterwegs verloren.",
    expireeReessayer: "Nochmal versuchen",
    expireeAutre: "Anderer Weg",
    titreFenetreConnexion: "Anmelden · Win or Workout",
    overlayTitre: "Feld · Win or Workout",
    overlayJoue: "heute Abend gespielt, ohne Menüs",
    overlayPasDePartie: "keine Partie",
    overlaySiGagne: "Bei Sieg",
    overlaySiPerdu: "Bei Niederlage",
    overlayEnAttente: "Offen",
    overlayConsigne: "Zieh mich hin, wo du willst, dann « Fertig ».",
    overlayPartieEnCours: "Partie läuft",
    overlayJeuOuvert: "heute Abend geöffnet, mit Menüs",
    overlayEscouade: "Trupp",
    trayOuvrir: "Win or Workout öffnen",
    trayOverlay: "Feld im Spiel",
    trayDossierCaptures: "Ordner mit den Aufnahmen öffnen",
    trayLireEcran: "Die Zahlen auf dem Bildschirm lesen",
    trayLirePendant: "Während der Partie mitlesen",
    trayBascule: "Feld ein- / ausblenden",
    trayCapturer: "Bildschirm aufnehmen",
    veilleTitre: "Win or Workout läuft im Hintergrund weiter",
    veilleCorps: "Deine Partien werden weiter erkannt. Klick auf das Symbol neben der Uhr, um es wieder zu öffnen, oder auf « Beenden », um es zu stoppen.",
    trayQuitter: "Beenden",
    captureFaite: "Aufnahme gespeichert",
    captureRatee: "Aufnahme nicht möglich",
    captureRaisonInconnue: "Grund unbekannt",
  },
  zh: {
    attenteTitre: "正在登录",
    attenteCorps: "请在浏览器里完成登录。",
    attenteAuto: "登录成功后，这个窗口会自动更新。",
    attenteRien: "没有反应？",
    attenteRouvrir: "重新打开浏览器",
    attenteRetour: "回到登录页",
    portTitre: "无法登录",
    portCorps: "这台电脑上已经有另一个 Win or Workout 在运行，多半是旧版本。",
    portConseil: "请把它彻底关掉，再重新启动这一个。否则登录会被它接走。",
    expireeTitre: "登录没有完成",
    expireeCorps: "浏览器没有把登录结果交回应用。可能是没走完流程，也可能是返回的消息在路上丢了。",
    expireeReessayer: "重试",
    expireeAutre: "换一种方式",
    titreFenetreConnexion: "登录 · Win or Workout",
    overlayTitre: "小窗 · Win or Workout",
    overlayJoue: "今晚游戏时间，不含菜单",
    overlayPasDePartie: "没有进行中的对局",
    overlaySiGagne: "赢了",
    overlaySiPerdu: "输了",
    overlayEnAttente: "待还",
    overlayConsigne: "把我拖到你想要的位置，然后点「完成」。",
    overlayPartieEnCours: "对局进行中",
    overlayJeuOuvert: "今晚游戏开启时间，含菜单",
    overlayEscouade: "小队",
    trayOuvrir: "打开 Win or Workout",
    trayOverlay: "游戏内小窗",
    trayDossierCaptures: "打开截图文件夹",
    trayLireEcran: "读取屏幕上的数字",
    trayLirePendant: "对局期间读取屏幕",
    trayBascule: "显示 / 隐藏小窗",
    trayCapturer: "截取屏幕",
    veilleTitre: "Win or Workout 仍在后台运行",
    veilleCorps: "对局仍在被检测。点击时钟旁边的图标可以重新打开，选择「退出」则完全停止。",
    trayQuitter: "退出",
    captureFaite: "截图已保存",
    captureRatee: "截图失败",
    captureRaisonInconnue: "原因不明",
  },
  ja: {
    attenteTitre: "ログインしています",
    attenteCorps: "ブラウザでログインを完了してください。",
    attenteAuto: "ログインが済むと、このウィンドウは自動で切り替わります。",
    attenteRien: "何も起きませんか？",
    attenteRouvrir: "ブラウザをもう一度開く",
    attenteRetour: "ログイン画面に戻る",
    portTitre: "ログインできません",
    portCorps: "このパソコンでは、別の Win or Workout がすでに動いています。おそらく古いバージョンです。",
    portConseil: "そちらを完全に閉じてから、こちらを起動し直してください。そのままだと、ログインはそちらに届きます。",
    expireeTitre: "ログインが完了していません",
    expireeCorps: "ブラウザからアプリにログイン結果が返ってきませんでした。手続きが終わらなかったか、返信が途中で失われたかのどちらかです。",
    expireeReessayer: "もう一度試す",
    expireeAutre: "別の方法",
    titreFenetreConnexion: "ログイン · Win or Workout",
    overlayTitre: "パネル · Win or Workout",
    overlayJoue: "今夜のプレイ時間（メニューを除く）",
    overlayPasDePartie: "試合なし",
    overlaySiGagne: "勝った場合",
    overlaySiPerdu: "負けた場合",
    overlayEnAttente: "未払い",
    overlayConsigne: "好きな場所へドラッグして、「完了」を押してください。",
    overlayPartieEnCours: "試合中",
    overlayJeuOuvert: "今夜の起動時間（メニュー含む）",
    overlayEscouade: "スクワッド",
    trayOuvrir: "Win or Workout を開く",
    trayOverlay: "ゲーム中のパネル",
    trayDossierCaptures: "スクリーンショットのフォルダーを開く",
    trayLireEcran: "画面の数字を読み取る",
    trayLirePendant: "試合中に画面を読み取る",
    trayBascule: "パネルの表示 / 非表示",
    trayCapturer: "画面を撮影",
    veilleTitre: "Win or Workout はバックグラウンドで動いています",
    veilleCorps: "試合の検出は続いています。時計の横のアイコンをクリックすると開き直せます。止めるときは「終了」を選んでください。",
    trayQuitter: "終了",
    captureFaite: "スクリーンショットを保存しました",
    captureRatee: "スクリーンショットを保存できません",
    captureRaisonInconnue: "原因不明",
  },
};

/**
 * Les textes d'une langue. Une langue inconnue retombe sur l'anglais, jamais
 * sur du vide et jamais sur le français : le français est la langue de celui
 * qui écrit l'application, en faire le repli revient à ne jamais voir le
 * défaut.
 */
function textes(langue) {
  return TEXTES[choisirLangue(langue)] ?? TEXTES[REPLI];
}

module.exports = { TEXTES, textes };
